### ISSUE TITLE
Should pass the “February 30” test

### ISSUE THREAD

**Issue by natesilva** [SamVerschueren/vali-date#1]
```javascript
console.log(validate('2016-02-30T03:04:05Z'));
// true
```

**Comment by SamVerschueren** [comment]
Would do you mean? That it should return `false`? This library only checks the format. Also, `new Date('2016-02-30T03:04:05Z')` results in `2016-03-01T03:04:05Z`.

Maybe I should change the description to `Returns a boolean indicating if the date **format** provided is valid or not.`

**Comment by natesilva** [comment]
Okay. I was hoping it would tell me if the date is valid.

I’m looking to answer the question, “is this a valid date?”. But most date validation libraries instead answer the question “can this be converted to a JavaScript Date object?”. Unfortunately JavaScript accepts invalid dates and arbitrarily converts them to other dates.

Answering the first question is really hard because it involves doing your own string parsing instead of relying on `Date` to do it.
